services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        PORT: ${SERVER_PORT}
        WS_PORT: ${WS_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WS_PORT}:${WS_PORT}"
    environment:
      NODE_ENV: ${ENVIRONMENT}
      PORT: ${SERVER_PORT}
      WS_PORT: ${WS_PORT}
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        VUE_APP_API_URL: ${VUE_APP_API_URL}
        VUE_APP_WS_URL: ${VUE_APP_WS_URL}
        VUE_APP_IMAGES_URL: ${VUE_APP_IMAGES_URL}
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      NODE_ENV: ${ENVIRONMENT}
      VUE_APP_API_URL: ${VUE_APP_API_URL}
      VUE_APP_WS_URL: ${VUE_APP_WS_URL}
      VUE_APP_IMAGES_URL: ${VUE_APP_IMAGES_URL}
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
