services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${WS_PORT}:${WS_PORT}"
    environment:
      NODE_ENV: production
      PORT: ${SERVER_PORT}
      WS_PORT: ${WS_PORT}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
        VUE_APP_API_URL: ${VUE_APP_API_URL}
        VUE_APP_WS_URL: ${VUE_APP_WS_URL}
        VUE_APP_IMAGES_URL: ${VUE_APP_IMAGES_URL}
    ports:
      - "${CLIENT_PORT}:80" # Порт клиента (Nginx)
    environment:
      NODE_ENV: production
      VUE_APP_API_URL: ${VUE_APP_API_URL}
      VUE_APP_WS_URL: ${VUE_APP_WS_URL}
      VUE_APP_IMAGES_URL: ${VUE_APP_IMAGES_URL}
    depends_on:
      - server
