version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=3001

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_URL=http://server:3000
      - VUE_APP_IMAGES_URL=http://server:3000/images
    depends_on:
      - server
