services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
